screen:
  width: 700
  height: 1000

game:
  max_lives: 3
  max_asteroids: 10
  max_steps_per_episode: 5000

reward:
  player_died: 50.0
  survive_step: 0.01
  idle_penalty: -0.001

rl:
  observation_radius: 500.0
  max_episode_steps: 5000
  normalize_observation: true
